create table uploaded_data.ece_student_data
(
	source_child_id varchar(100),
	funding_id int,
	organization_id int,
	organization_name varchar(255),
	site_id int,
	site_name varchar(255),
	facility_code int,
	site_region varchar(20),
	title_one boolean,
	site_license_number int,
	enrollment_id int,
	family_determination_id int,
	family_id int,
	reporting_period date,
	reporting_period_start date,
	reporting_period_end date,
	has_sasid boolean,
	funding_space_id int,
	first_reporting_period date,
	last_reporting_period date,
	family_det_id double precision,
	birth_month date,
	is_born_in_ct boolean,
	foster varchar(20),
	american_indian_or_alaska_native boolean,
	asian boolean,
	black_or_african_american boolean,
	native_hawaiian_or_pacific_islander boolean,
	white boolean,
	hispanic_or_latinx_ethnicity varchar(20),
	gender varchar(20),
	dual_language_learner varchar(20),
	receives_disability_services varchar(20),
	family_town varchar(255),
	family_state varchar(255),
	family_zip_code varchar(255),
	family_homelessness varchar(20),
	funding_space_time varchar(50),
	funding_space_age_group varchar(50),
	funding_source varchar(20),
	enrollment_age_group text,
	enrollment_entry date,
	enrollment_exit date,
	family_size int,
	family_income double precision,
	family_income_not_disclosed boolean
);


