version: "3.7"
services:

  superset:
    env_file: ./docker/.env
    image: apache/superset
    container_name: superset
    volumes:
      - ./config:/app/pythonpath
      - ./images:/app/superset/static/assets/images/mounted_images/
      - ./cache:/cache
    ports:
      - "0.0.0.0:8088:8080"
