version: 2.1

jobs: 
  deploy:
    machine:
      image: ubuntu-1604:202007-01 
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: 'Install dependencies'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "sudo apt-get install build-essential libssl-dev libffi-dev python3-dev python3-pip libsasl2-dev libldap2-dev"
      - run:
          name: 'Create Python Virtual Env'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "pip install virtualenv && python3 -m venv venv && . venv/bin/activate"
      - run:
          name: 'Install SuperSet'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "pip install apache-superset"
      - run:
          name: 'Initialize the SuperSet Database'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "superset db upgrade"
      - run:
          name: 'Load examples'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "superset load_examples"
      - run:
          name: 'Set default roles and permissions'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "superset init"
      - run:
          name: 'Start SuperSet'
          command: |
            ssh ec2-user@ec2-18-225-6-36.us-east-2.compute.amazonaws.com "superset runserver -p 8080"

workflows:
  deploy-staging:
    jobs:
      - deploy