version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.1

jobs: 
  build:
    parameters:
      env:
        description: 'The environment to deploy Superset to (staging or prod)'
        type: string
    machine:
      image: ubuntu-1604:202007-01 
    steps:
      - checkout
      - run:
          name: 'Remove Postgres Password set up from env file'
          command: |
            sed -i '/POSTGRES_PASSWORD/d' docker/.env
      - run:
          name: 'Add DB Password to config files'
          command: |
             SUPERSET_DB_PASS=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/db/password --query 'SecretString' --output text) && echo -e "POSTGRES_PASSWORD=$SUPERSET_DB_PASS" >> docker/.env
      - run:
          name: 'Add Mapbox key to config file'
          command: |
            MAPBOX_KEY=$(aws secretsmanager get-secret-value --secret-id /data-viz/map_box/key --query 'SecretString' --output text) && echo -e "MAPBOX_KEY=$MAPBOX_KEY" >> docker/.env
      # Save workspace for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    parameters:
      env:
        description: 'The environment to deploy Superset to (staging or prod)'
        type: string
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - eb/deploy:
          environment-name: ece-pensieve-<< parameters.env >>-env
          platform-version: docker
          
workflows:
  deploy-prod:
    jobs:
      - hold:
          type: approval
      - build:
          env: prod
          requires:
            - hold
      - deploy:
          env: prod
          requires:
            - build
  deploy-staging:
    jobs:
      - hold:
          type: approval
      - build:
          env: staging
          requires:
            - hold
      - deploy:
          env: staging
          requires:
            - build