version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs: 
  build:
    parameters:
      env:
        description: 'The environment to deploy Superset to (staging or prod)'
        type: string   
    machine:
      image: ubuntu-1604:202007-01 
    steps:
      - checkout
      - run:
          name: 'Set Postgres DB Password from Secrets Manager'  
          command: |
            sed -i '/POSTGRES_PASSWORD/d' docker/.env
            SUPERSET_DB_PASS=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/db/password --query 'SecretString' --output text) && echo -e "POSTGRES_PASSWORD=$SUPERSET_DB_PASS" >> docker/.env
      - run:
          name: 'Set Postgres DB Host'
          command: |
            sed -i '/POSTGRES_HOST/d' docker/.env
            echo -e "POSTGRES_HOST=<< parameters.env >>.ece-pensieve-db.ctoecskylight.com" >> docker/.env
      - run:
          name: 'Set Admin Password for Superset from Secrets Manager'
          command: |
            sed -i '/ADMIN_PASSWORD/d' docker/.env
            SUPERSET_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value --secret-id /pensieve/<< parameters.env >>/superset/admin/password --query 'SecretString' --output text) && echo -e "ADMIN_PASSWORD=$SUPERSET_ADMIN_PASSWORD" >> docker/.env
      - run:
          name: 'Add Mapbox key to config file'
          command: |
            MAPBOX_KEY=$(aws secretsmanager get-secret-value --secret-id /data-viz/map_box/key --query 'SecretString' --output text) && echo -e "MAPBOX_KEY=$MAPBOX_KEY" >> docker/.env
      # Save workspace for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    parameters:
      env:
        description: 'The environment to deploy Superset to (staging or prod)'
        type: string
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - eb/setup
      - run:
          name: Initialize Elastic Beanstalk
          command: eb init ece-pensieve-<< parameters.env >>-app --region us-east-2 --platform docker
      - run:
          name: Deploy to Elastic Beanstalk environment
          command: eb deploy ece-pensieve-<< parameters.env >>-env

  setup-admin-user:
    parameters:
      env:
        description: 'The environment to deploy Superset to (staging or prod)'
        type: string
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - eb/setup
      - add_ssh_keys
      - run:
          name: Create admin user
          command: |
            ls -la
            eb ssh ece-pensieve-<< parameters.env >>-env --command "docker exec -it superset superset fab create-admin --username 'voldemort' --firstname 'ADMIN' --lastname 'USER' --email 'admin@ctoec.org' --password 'password'"
          
workflows:
  deploy-prod:
    jobs:
      - hold:
          type: approval
      - build:
          env: prod
          requires:
            - hold
      - deploy:
          env: prod
          requires:
            - build
      - setup-admin-user:
          env: prod
          requires:
            - deploy
  deploy-staging:
    jobs:
      - hold:
          type: approval
      - build:
          env: staging
          requires:
            - hold
      - deploy:
          env: staging
          requires:
            - build
      - setup-admin-user:
          env: staging
          requires:
            - deploy