version: "3.7"
services:

  db:
    env_file: .env
    # Currently using Postgres 10, this can be updated if needed
    image: postgis/postgis:10-2.5-alpine
    container_name: superset_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      # File system is mounted on volume vol-067000fe41671b6b0 (Initially mounted using steps here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html)
      - ./postgres_data_mounted:/var/lib/postgresql/data

  superset:
    env_file: .env
    image: apache/incubator-superset
    container_name: superset
    volumes:
      - ./config:/app/pythonpath
      - ./images:/app/superset/static/assets/images/mounted_images/
      - ./cache:/cache
    ports:
      - "8088:8080"
